### ISSUE TITLE
No module named 'schulze_helper'

### ISSUE THREAD

**Issue by theonaciri** [bradbeattie/python-vote-core#24]
Hi, I was unable to launch the project.
The installation of the file setup.py outlines 2 syntax errors.

`sudo python setup.py build /* normal */` 
`sudo python setup.py install`

> [...]
byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/schulze_helper.py to schulze_helper.cpython-35.pyc
  File "build/bdist.linux-x86_64/egg/pyvotecore/schulze_helper.py", line 119
    print "Proportional completion broke (went from %s to %s)" % (weight_sum, sum(profile.values()))
                                                             ^
SyntaxError: invalid syntax

>byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/tie_breaker.py to tie_breaker.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/schulze_npr.py to schulze_npr.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/plurality_at_large.py to plurality_at_large.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/schulze_pr.py to schulze_pr.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/schulze_stv.py to schulze_stv.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/common_functions.py to common_functions.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/abstract_classes.py to abstract_classes.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyvotecore/plurality.py to plurality.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying python_vote_core.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_vote_core.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_vote_core.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_vote_core.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_vote_core.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python_vote_core.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/python_vote_core-20120423.0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing python_vote_core-20120423.0-py3.5.egg
removing '/usr/lib/python3.5/site-packages/python_vote_core-20120423.0-py3.5.egg' (and everything under it)
creating /usr/lib/python3.5/site-packages/python_vote_core-20120423.0-py3.5.egg
Extracting python_vote_core-20120423.0-py3.5.egg to /usr/lib/python3.5/site-packages
  File "/usr/lib/python3.5/site-packages/python_vote_core-20120423.0-py3.5.egg/pyvotecore/schulze_helper.py", line 119
    print "Proportional completion broke (went from %s to %s)" % (weight_sum, sum(profile.values()))
                                                             ^
>SyntaxError: invalid syntax

>python-vote-core 20120423.0 is already the active version in easy-install.pth

>Installed /usr/lib/python3.5/site-packages/python_vote_core-20120423.0-py3.5.egg
Processing dependencies for python-vote-core==20120423.0
Searching for python-graph-core==1.8.2
Best match: python-graph-core 1.8.2
Processing python_graph_core-1.8.2-py3.5.egg
python-graph-core 1.8.2 is already the active version in easy-install.pth

>Using /usr/lib/python3.5/site-packages/python_graph_core-1.8.2-py3.5.egg
Finished processing dependencies for python-vote-core==20120423.0

I then try using the example provided using python2 or 3
`>>> from pyvotecore.schulze_method import SchulzeMethod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/Projects/TestNode/test/python-vote-core/pyvotecore/schulze_method.py", line 16, in <module>
    from schulze_helper import SchulzeHelper
ImportError: No module named 'schulze_helper'`

Is it my configuration or a problem from the depository ?

**Comment by dukebody** [comment]
Looks like python-vote-core works only under Python 2. Install and use it using python2.

**Comment by theonaciri** [comment]
Oh nooooo. I didn't try installing it with python2, I only tried launching it. My bad.

**Comment by jhpratt** [comment]
@theonaciri If you're interested, I'm hosting a python3 compatible version. It wasn't written by me, but I'll be maintaining it.
