### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by ppKrauss** [bradbeattie/python-vote-core#31]
Hi, I am new here. I see the project at [modernballots.com](https://modernballots.com) and [@solstag tips](https://discuss.okfn.org/t/votacao-por-metodo-schulze/3469/4?u=ppkrauss)...

There are a way to translate online services to portuguese (pt-BR)? We can help to translate.

**Comment by bradbeattie** [comment]
Hey, the code-base that modernballots run on is somewhat antiquated at this point and in need of a full re-write from the ground up. I think you'd have better luck in trying to write a new site using python-vote-core as a base  than waiting on me to potentially bring modernballots.com up to speed where it can be easily translated.
