### ISSUE TITLE
Examples for using other voting methods?

### ISSUE THREAD

**Issue by erelsgl** [bradbeattie/python-vote-core#36]
I managed to used SchulzeMethod with the help of the example. But, I ran similar code for Plurality and IRV, and it did not work. Is there a simple example for running these methods?

**Comment by robinharms** [comment]
Hi, if you want simple examples, check the tests!

**Comment by erelsgl** [comment]
Thanks! The tests are indeed helpful. It is confusing that each method accepts its input in a different shape..

**Comment by robinharms** [comment]
Not really something any of us can change, since they need different data to run.

I'm closing the issue since it hasn't got anything to do with the code.
